# Electron with Webpack pipeline
# using yarn to get packages and build

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run dist-win
  displayName: 'building app for Windows platform'

- task: CopyFiles@2
  inputs:
    contents: '$(Pipeline.Workspace)/s/dist/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'brs-emu-app-windows'
